# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/8.4/metricbeat-module-elasticsearch.html

- module: elasticsearch
  metricsets:
    - node
    - node_stats
    - index
    - shard
  period: 01s
  hosts: ["https://192.168.1.221:9200"]
  username: "elastic"
  password: "elastic"

  ssl.certificate_authorities: ["/etc/elasticsearch/certs/http_ca.crt"]
  xpack.enabled: true
