---
- name: Installing Filebeat on Elasticsearch servers
  hosts: elk
  tasks:
    - name: "Clearing residual Packages if any Before Installation"
      yum:
        name: filebeat
        state: absent
    
    - name: Cleaning up Residual Files if any
      file:
        path: ~/kibana-stuff/filebeat
        state: absent  

    - name: Making Temp Directory for packages 
      file:
        path: ~/kibana-stuff/filebeat
        state: directory
        mode: '0755'
        recurse: yes

    - name: Downloading Filebeat
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.17.7-x86_64.rpm
        dest: ~/kibana-stuff/filebeat
        mode: '0755'
      register: dwl 

    - name: Getting the output
      debug:
        var: dwl

    - name: Installing Filebeat
      shell: cd ~/kibana-stuff/filebeat && rpm -iv filebeat-7.17.7-x86_64.rpm
      register: install_log

    - name: Status of Installation
      debug:
        var: install_log

    - name: Checking if its actually installed
      yum:
        list: filebeat
      register: chk 

    - name: Installation Failed, Check System Logs for Issue
      fail:
        msg: 'Failed Because the package was not found'
      when: chk.failed == true
    
    - name: Downloading the filebeat Configs
      get_url:
        url: "{{ item }}"
        dest: ~/kibana-stuff/filebeat
        mode: '0755'
      loop: 
        - https://raw.githubusercontent.com/methos28/ElasticSearch/main/Beats_Configs/Filebeat/elasticsearch.yml
        - https://raw.githubusercontent.com/methos28/ElasticSearch/main/Beats_Configs/Filebeat/filebeat.yml
        - https://raw.githubusercontent.com/methos28/ElasticSearch/main/Beats_Configs/Filebeat/system.yml
      register: dwl_cnf

    - name: Download Status
      debug:
        var: dwl_cnf

    - name: 
      copy:
        src: ~/kibana-stuff/filebeat/filebeat.yml
        dest: /etc/filebeat/
        mode: '0755'
        remote_src: true

    - name: Enabling Elasticsearch Modules
      shell: filebeat modules enable elasticsearch system
      register: sts 

    - name: Status of Above task
      debug:
        var: sts
    
    - name: Copying the Elasticsearch Module Config
      copy:
        src: ~/kibana-stuff/filebeat/{{ item }}
        dest: /etc/filebeat/modules.d/
        mode: '0755'
        remote_src: true
      loop:
        - elasticsearch.yml
        - system.yml
    

    - name: Enabling and Starting the Service
      systemd:
        state: restarted 
        daemon-reload: yes
        name: filebeat
        enabled: yes 
      register: sysctl

    - name: Reload Status
      debug:
        var: sysctl 


          
      


           
